### ISSUE TITLE
Nginx timezone not matched with the host

### ISSUE THREAD

**Issue by GeeMing** [usoftopen/docker-lnmp#1]
当再nginx启用 autoindex 时候，发现目录文件的时间和实际显示不匹配，无论有无设置`autoindex_localtime` 
之后在 _docker_compose.yml_ 添加了一行映射 `- /etc/localtime:/etc/localtime:ro` 重新编译运行，可以显示正确本地时间。

是否可以需要这样解决nginx和宿主机时区不一致问题，还是有其他考虑因素要用其他解决方法？

**Comment by usoftglobal** [comment]
可以这样搞
